### ISSUE TITLE
warnings load_ba_results

### ISSUE THREAD

**Issue by apaijmans** [matthewkling/flowR#1]
Hello,
When importing my BayesAss output file into R using load_ba_results, I get some warnings. As far as I can tell, it still seems to work OK, but nevertheless I thought I would mention it here.
The warning message is this:

```
`mutate_each()` is deprecated.
Use `mutate_all()`, `mutate_at()` or `mutate_if()` instead.
To map `funs` over all variables, use `mutate_all()`
`mutate_each()` is deprecated.
Use `mutate_all()`, `mutate_at()` or `mutate_if()` instead.
To map `funs` over all variables, use `mutate_all()`
Warning message:
In readLines(path) :
  incomplete final line found on 'Analyses/BayesAss/8pops/output_gaz_04.txt'
```
Not sure about the incomplete final line, the raw output file looks fine.

Hope this helps!

Thanks,
Anneke

**Comment by matthewkling** [comment]
Thanks for letting me know. Not sure about the last warning but the others are not worrisome as they simply stem from slightly outdated `dplyr` functions. I'm not actively updating this project at this time, but I will address these warnings if I resume work on the package. Hope you found the function to be of some use!

**Comment by apaijmans** [comment]
Yes, very useful, I also used the BA_deviance function (no warnings there). Thanks!
